// Code generated by dagger. DO NOT EDIT.

package main

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"os"
	"sort"

	"github.com/vektah/gqlparser/v2/gqlerror"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/sdk/resource"
	semconv "go.opentelemetry.io/otel/semconv/v1.37.0"
	"go.opentelemetry.io/otel/trace"

	"dagger/git-repo/internal/dagger"
	"dagger/git-repo/internal/querybuilder"
	"dagger/git-repo/internal/telemetry"
)

var dag = dagger.Connect()

func Tracer() trace.Tracer {
	return otel.Tracer("dagger.io/sdk.go")
}

// used for local MarshalJSON implementations
var marshalCtx = context.Background()

// called by main()
func setMarshalContext(ctx context.Context) {
	marshalCtx = ctx
	dagger.SetMarshalContext(ctx)
}

type DaggerObject = querybuilder.GraphQLMarshaller

type ExecError = dagger.ExecError

// ptr returns a pointer to the given value.
func ptr[T any](v T) *T {
	return &v
}

// convertSlice converts a slice of one type to a slice of another type using a
// converter function
func convertSlice[I any, O any](in []I, f func(I) O) []O {
	out := make([]O, len(in))
	for i, v := range in {
		out[i] = f(v)
	}
	return out
}

func (r GitRepo) MarshalJSON() ([]byte, error) {
	var concrete struct {
		DefaultBranch string
		SSH           *dagger.Socket
		Src           *dagger.Directory
	}
	concrete.DefaultBranch = r.DefaultBranch
	concrete.SSH = r.SSH
	concrete.Src = r.Src
	return json.Marshal(&concrete)
}

func (r *GitRepo) UnmarshalJSON(bs []byte) error {
	var concrete struct {
		DefaultBranch string
		SSH           *dagger.Socket
		Src           *dagger.Directory
	}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	r.DefaultBranch = concrete.DefaultBranch
	r.SSH = concrete.SSH
	r.Src = concrete.Src
	return nil
}

func (r VersionInfo) MarshalJSON() ([]byte, error) {
	var concrete struct {
		Commit  string
		Version string
	}
	concrete.Commit = r.Commit
	concrete.Version = r.Version
	return json.Marshal(&concrete)
}

func (r *VersionInfo) UnmarshalJSON(bs []byte) error {
	var concrete struct {
		Commit  string
		Version string
	}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	r.Commit = concrete.Commit
	r.Version = concrete.Version
	return nil
}

func (r Remote) MarshalJSON() ([]byte, error) {
	var concrete struct {
		Owner string
		Repo  string
	}
	concrete.Owner = r.Owner
	concrete.Repo = r.Repo
	return json.Marshal(&concrete)
}

func (r *Remote) UnmarshalJSON(bs []byte) error {
	var concrete struct {
		Owner string
		Repo  string
	}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	r.Owner = concrete.Owner
	r.Repo = concrete.Repo
	return nil
}

type registryAuthImpl struct {
	query *querybuilder.Selection
	id    *RegistryAuthID
}

type RegistryAuthID string

func LoadRegistryAuthFromID(r *dagger.Client, id RegistryAuthID) RegistryAuth {
	q := querybuilder.Query().Client(r.GraphQLClient())
	q = q.Select("loadGitRepoRegistryAuthFromID")
	q = q.Arg("id", id)
	return &registryAuthImpl{query: q}
}

func (r *registryAuthImpl) WithGraphQLQuery(q *querybuilder.Selection) RegistryAuth {
	return &registryAuthImpl{query: q}
}

func (r *registryAuthImpl) XXX_GraphQLType() string {
	return "RegistryAuth"
}

func (r *registryAuthImpl) XXX_GraphQLIDType() string {
	return "RegistryAuthID"
}

func (r *registryAuthImpl) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *registryAuthImpl) MarshalJSON() ([]byte, error) {
	if r == nil {
		return []byte("\"\""), nil
	}
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}

func (r *registryAuthImpl) UnmarshalJSON(bs []byte) error {
	var id RegistryAuthID
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = *LoadRegistryAuthFromID(dag, id).(*registryAuthImpl)
	return nil
}

func (r *registryAuthImpl) toIface() RegistryAuth {
	if r == nil {
		return nil
	}
	return r
}

func (r *registryAuthImpl) ID(ctx context.Context) (RegistryAuthID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")
	var response RegistryAuthID
	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

func (r *registryAuthImpl) From(address string) *dagger.Container {
	q := r.query.Select("from")
	q = q.Arg("address", address)

	return (&dagger.Container{}).WithGraphQLQuery(q)
}

func main() {
	ctx := context.Background()

	// Direct slog to the new stderr. This is only for dev time debugging, and
	// runtime errors/warnings.
	slog.SetDefault(slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{
		Level: slog.LevelWarn,
	})))

	if err := dispatch(ctx); err != nil {
		os.Exit(2)
	}
}

func convertError(rerr error) *dagger.Error {
	if gqlErr := findSingleGQLError(rerr); gqlErr != nil {
		dagErr := dag.Error(gqlErr.Message)
		if gqlErr.Extensions != nil {
			keys := make([]string, 0, len(gqlErr.Extensions))
			for k := range gqlErr.Extensions {
				keys = append(keys, k)
			}
			sort.Strings(keys)
			for _, k := range keys {
				val, err := json.Marshal(gqlErr.Extensions[k])
				if err != nil {
					fmt.Println("failed to marshal error value:", err)
				}
				dagErr = dagErr.WithValue(k, dagger.JSON(val))
			}
		}
		return dagErr
	}
	return dag.Error(rerr.Error())
}

func findSingleGQLError(rerr error) *gqlerror.Error {
	switch x := rerr.(type) {
	case *gqlerror.Error:
		return x
	case interface{ Unwrap() []error }:
		return nil
	case interface{ Unwrap() error }:
		return findSingleGQLError(x.Unwrap())
	default:
		return nil
	}
}
func dispatch(ctx context.Context) (rerr error) {
	ctx = telemetry.InitEmbedded(ctx, resource.NewWithAttributes(
		semconv.SchemaURL,
		semconv.ServiceNameKey.String("dagger-go-sdk"),
		// TODO version?
	))
	defer telemetry.Close()

	// A lot of the "work" actually happens when we're marshalling the return
	// value, which entails getting object IDs, which happens in MarshalJSON,
	// which has no ctx argument, so we use this lovely global variable.
	setMarshalContext(ctx)

	fnCall := dag.CurrentFunctionCall()
	defer func() {
		if rerr != nil {
			if err := fnCall.ReturnError(ctx, convertError(rerr)); err != nil {
				fmt.Println("failed to return error:", err, "\noriginal error:", rerr)
			}
		}
	}()

	parentName, err := fnCall.ParentName(ctx)
	if err != nil {
		return fmt.Errorf("get parent name: %w", err)
	}
	fnName, err := fnCall.Name(ctx)
	if err != nil {
		return fmt.Errorf("get fn name: %w", err)
	}
	parentJson, err := fnCall.Parent(ctx)
	if err != nil {
		return fmt.Errorf("get fn parent: %w", err)
	}
	fnArgs, err := fnCall.InputArgs(ctx)
	if err != nil {
		return fmt.Errorf("get fn args: %w", err)
	}

	inputArgs := map[string][]byte{}
	for _, fnArg := range fnArgs {
		argName, err := fnArg.Name(ctx)
		if err != nil {
			return fmt.Errorf("get fn arg name: %w", err)
		}
		argValue, err := fnArg.Value(ctx)
		if err != nil {
			return fmt.Errorf("get fn arg value: %w", err)
		}
		inputArgs[argName] = []byte(argValue)
	}

	result, err := invoke(ctx, []byte(parentJson), parentName, fnName, inputArgs)
	if err != nil {
		return err
	}
	resultBytes, err := json.Marshal(result)
	if err != nil {
		return fmt.Errorf("marshal: %w", err)
	}

	if err := fnCall.ReturnValue(ctx, dagger.JSON(resultBytes)); err != nil {
		return fmt.Errorf("store return value: %w", err)
	}
	return nil
}
func invoke(ctx context.Context, parentJSON []byte, parentName string, fnName string, inputArgs map[string][]byte) (_ any, err error) {
	_ = inputArgs
	switch parentName {
	case "GitRepo":
		switch fnName {
		case "GitContainer":
			var parent GitRepo
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*GitRepo).GitContainer(&parent, ctx)
		case "Remote":
			var parent GitRepo
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*GitRepo).Remote(&parent, ctx)
		case "SetVersion":
			var parent GitRepo
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var registryAuth *registryAuthImpl
			if inputArgs["registryAuth"] != nil {
				err = json.Unmarshal([]byte(inputArgs["registryAuth"]), &registryAuth)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg registryAuth", err))
				}
			}
			return (*GitRepo).SetVersion(&parent, ctx, registryAuth.toIface())
		case "VersionInfo":
			var parent GitRepo
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*GitRepo).VersionInfo(&parent, ctx)
		case "":
			var parent GitRepo
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var defaultBranch string
			if inputArgs["defaultBranch"] != nil {
				err = json.Unmarshal([]byte(inputArgs["defaultBranch"]), &defaultBranch)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg defaultBranch", err))
				}
			}
			var src *dagger.Directory
			if inputArgs["src"] != nil {
				err = json.Unmarshal([]byte(inputArgs["src"]), &src)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg src", err))
				}
			}
			var ssh *dagger.Socket
			if inputArgs["ssh"] != nil {
				err = json.Unmarshal([]byte(inputArgs["ssh"]), &ssh)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg ssh", err))
				}
			}
			return New(defaultBranch, src, ssh), nil
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	default:
		return nil, fmt.Errorf("unknown object %s", parentName)
	}
}
